ALTER TABLE public.pets
    ADD COLUMN breed VARCHAR(100),
    ADD COLUMN gender VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
    ADD COLUMN birth_date DATE,
    ADD COLUMN activity_level VARCHAR(30),
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;