spring:
  application:
    name: petly-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/petly
    username: petly
    password: petly_dev_password

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080